language: go

go:
  - "1.10.x"
  - release
  - master
  - tip

os:
  - linux
  - osx

services:
  - securelink

env:
 - GO111MODULE=on

install:
  - go get -v ./...

script:
  - go test -race -v -cover ./...