language: go

go:
  - "1.11.x"
  - master
  - tip

os:
  - linux
  - osx

services:
  - securelink

install:
  - npm install -g codeclimate-test-reporter
  - go get -v ./...

script:
  - go test -race -v -cover -coverprofile=coverage.out ./...
  - codeclimate-test-reporter < coverage.out