language: go

go:
  - "1.11.x"
  - master

os:
  - linux
  - osx

services:
  - securelink

install:
  - npm install -g codeclimate-test-reporter
  - go get -v ./...

script:
  # - go test -race -v -cover -coverprofile=cov.out
  # - codeclimate-test-reporter < cov.out
  - ./test_script.sh