language: go
go:
  - 1.11.x
  - master
os:
  - linux
  - osx
services:
- secureli  nk
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get -v ./...
script:
  - echo $COVERALLS_TOKEN

  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
env:
  global:
    - GO111MODULE: "on"
    # Provides the coveralls.io token $COVERALLS_TOKEN
    - secure: MT+0t5A5o8a5dEc7oqNmY3l1SSn86wH8uRvzwAS6j493pJ0sO7o0OUsJfFX7Z4fbBbQp3JCmZEdAW+5umxlcTkTyudxPw3NAnvG0Q/DwfOlfL10gv60+F/hHw9vfHKu/bLpQWe1D9fqeb5gMwUXBVBxRiTDD48Aym6eEeR10y8M7jDTcKLUzOz6DKiL33f/fEWZFWmSamu+X4Wm4UGlW5lt8FoA7dOnYgbg+ABNefjp8rnV3/pnL86hwDxYmK/r/9Ia/XqVKHKkdJKGnEAiQHX03+/Hg8FVzrvElNTAK31KIkUXfGXGAY46AG65EAkgMB5GsBi0JqL4z+DYWNvWnpw/hc1eRZXNzBYuKkkYjieaUj9aKcGSE4tnCn3c8R8In/wEMHM+OrG4XAXMSet9X7eWWloNdnrFgR2YhVLTPJ8ZRXuqPqr/7zFXzyeljXdVvt3nsGHDpKuuB77Txon6n+LHc9KtluvDo9fNFMkpInCyCBDkRmUVeA4xSTiEBhR5d1egbuoVJySXbvBc71MFEOoqmMPLCHoh27Qzi7lTuoudS3CMyXqQ+CO5hPY+9yr2TBWcWhMwBmPHK36FKjVTbcSK+za9/mAyGWmkSrd2yQ/cgtixoD/Lno/rDPk40/v/d02mWtDwaUpdopO7g42y7xGBzD7KtVQ6DlY8HKvKTeW0=