# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    environment:
      GO111MODULE: "on"
    docker:
      # specify the version
      - image: circleci/golang:latest
      
    working_directory: /go/src/github.com/alexandrestein/securelink
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -race -cover -coverprofile=coverage.out -v ./...

      # - run:
      #     name: "Setup Code Climate test-reporter"
      #     command: |
      #       # download test reporter as a static binary
      #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #       chmod +x ./cc-test-reporter
      # - run:
      #     name: "Run tests"
      #     command: |
      #       # upload test report to Code Climate using `after-build`
      #       ./cc-test-reporter after-build --coverage-input-type clover --input coverage.out --exit-code $?